# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI (JDK 8)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Java
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64

      # Cache
      - name: Cache Gradle
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}"

      # Build
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      # Upload
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Guilds
          path: build/libs/Guilds-*-SNAPSHOT.jar
